### ISSUE TITLE
Question about semi-supervised setting

### ISSUE THREAD

**Issue by luochonghai** [Sunarker/Safeguarded-Dynamic-Label-Regression-for-Noisy-Supervision#5]
Hey bro, would you please release the code in the open-set noise & semi-supervised learning setting? 
Also I feel a little confused about these experiments.
Question 1: The paper in the journal version says, '**For the toy experiments that consider the open-set noisy labels, we randomly select 10,000 samples from the original data set and shuffle the order of the pixel values as the outliers**'. Does the sentence mean that outliers are generated synthetically by shuffling the original pixel orders of raw images? 
Question 2: The paper in the journal version says, '**In the semi-supervised learning, we utilize the clean labels of the first 5, 000 clean samples and the first 500 outlier samples for the training**'. Does the sentence mean that the labeled data set is composed of 5,000 clean samples, and the unlabeled data set is composed of 500 outliers?
Hope you could help me better understand the paper.
Many thx~

**Comment by Sunarker** [comment]
The codes are easily implemented based on the current codes. I am sorry that it is impossible for me now release the codes as I have graduated for such a long time. I am not sure that my codes are still stored in the server of my previous team.

For question 1, it is what you guess.

For question 2, the two numbers are both for labeled data (labels for clean samples and labels for outliers). For the remaining samples in the dataset, they are all noisily annotated.

**Comment by luochonghai** [comment]
> The codes are easily implemented based on the current codes. I am sorry that it is impossible for me now release the codes as I have graduated for such a long time. I am not sure that my codes are still stored in the server of my previous team.
> 
> For question 1, it is what you guess.
> 
> For question 2, the two numbers are both for labeled data (labels for clean samples and labels for outliers). For the remaining samples in the dataset, they are all noisily annotated.

Many thx (〃'▽'〃)~
